name: tiktoken
description: Tiktoken is a BPE tokeniser for use with OpenAI's models. It exposes APIs used for processing text using tokens.
homepage: https://marinvitlov.com
repository: https://github.com/mvitlov/tiktoken
issue_tracker: https://github.com/mvitlov/tiktoken/issues?q=is%3Aissue+is%3Aopen+
version: 1.0.2

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

